language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "your_organization_key"
    token:
      secure: "$SONAR_TOKEN"

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

before_install:
  - export TZ=Europe/Berlin
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
    -Dsonar.projectKey=emschu:oer-collector \
    -Dsonar.organization=emschu-github \
    -Dsonar.host.url=https://sonarcloud.io

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

