language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: sonarcloud
    token:
      secure: X8ARAIBfDC4bqOohNXHfuHGm3rJbrMTBpuZMmFn+uEifVEcTqKbGhekMBX18Br+QbK02SU8arzoonHiKsAzeHtJOdKWiI4QmVAdR43b7BLi+yzkAMytOmGzXLO9nYm9SfotrAuntU4RDuR3XW/EibWDgBDGAvdyHzCTf+CG5NcbBrusx8CKUhtIcfwig0eBfZIUVPU7hGsCGZABCB0pB1EvWnK2/gBuuGYpDsA8ypQjuu3s+t8V6/PWW7s42wuRR9DM+mfvB+P9Sx03AH/IRWyfrkotqjlqw3+Oa7WrDIGahhZEDSLU2ulIloWUTnCbOzGD81o8qj5DVOGsAUWUFKyQPVcmnwKNoMxi2Y+2TCDOILTM14BeOX7yYvKcWjENcmHZfdGHPlD/LApHk1BA99sLb9bhzmJtVIEnKkjZg2zIIRzB3c+5o/9tMb930eaPzAtykldzpU082WrE/ZfoutxGWb9bG45q3Ij+RRxhIe5tF4hsBn+L3Y2vcNgnWpRI5L0KieD0ViZb4zQXBTGjno3XerAokweXhxC6b/J+09vGepD7fB5wste+O1K6e/cEvIxWKHUMmVjP1WWTWJIxExBgOplNl6u54xrl7O8TF4AxaoYqMeO8DQ125uqqLvausKq0n7VLALPxRxn7geFJZPjXZHGxxLS0ap+awAhu0/mE=

before_install:
- export TZ=Europe/Berlin
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

