version: '2'
services:

  mariadb:
    image: mariadb:10
    hostname: database
    restart: always
    volumes:
      - oer-database-mariadb-data:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oer_program_data
      MYSQL_USER: oer_db_user
      MYSQL_PASSWORD: oer_db_pw

  squid_proxy:
    restart: on-failure
    build: squid
    hostname: proxy
    ports:
      - 3128

  oer_collector:
    build: oer_collector
    depends_on:
      - mariadb
      - squid_proxy
    links:
      - "mariadb:database"
    environment:
      JAVA_ARGS: -Djava.security.egd=file:/dev/./urandom

  oer_server:
    build: oer_server
    restart: on-failure
    links:
      - "mariadb:database"
    environment:
      JAVA_ARGS: -Djava.security.egd=file:/dev/./urandom
    depends_on:
      - mariadb
    ports:
      - "8081:8081"

volumes:
  oer-database-mariadb-data:
